language: scala
scala:
  - 2.12.8

jdk:
  - oraclejdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: tag IS present AND NOT fork

jobs:
  include:
    - stage: release
      env: JOB=Release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - target/repos

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
