name: Scalify
baseurl: /scalify
description: Build Shopify Apps using Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.21+10-4dccd5e4-SNAPSHOT
org: com.github.fulrich
markdown: kramdown
